### PR TITLE
Completed Task 1

### PR DESCRIPTION
**Pull request by Hariteja11**
successfully completed my CSEDGE task-1 i.e Landing page in Web Development internship

### CODE REVIEW

**Comment by Hariteja11** [comment]
I have completed my task-1

**Comment by Hariteja11** [comment]
successfully completed my CSEDGE task-2 i.e Gallery in Web Development internship

**Comment by Hariteja11** [comment]
successfully completed my CSEDGE task-3 i.e portfolio in Web Development internship

**Comment by Hariteja11** [comment]
successfully completed my CSEDGE task-4 i.e Student Enrollment Form

 in Web Development internship

**Comment by Hariteja11** [comment]
I have completed all the tasks successfully.

**Comment by CSEdgeOff** [comment]
Hello @Hariteja11 We've seen your video on YouTube..!

**Comment by Hariteja11** [comment]
Yaah I have posted a video is there any problem with it?

**Comment by CSEdgeOff** [comment]
@Hariteja11 Not at all!  If you'd like to make another video, you can! We've even updated our tasks. Check them out in the new repositories, which have also been updated on the website. There are exciting new things coming soon!

**Comment by Hariteja11** [comment]
Awesome, thank you so much!

**Pull request merged**
